apiVersion: v1
kind: Pod
metadata:
  name: affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - cpu-prod-worker17
  containers:
  - name: mycontainer
    image: ubuntu:20.04
    command: ["/bin/bash"]
    args: ["-c","ls /Ext;ls /data; ls /persistent;sleep 6000;echo bye!"]