trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'spring-backend'
  acrName: 'CG5677acr'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build React App'

- task: Docker@2
  inputs:
    containerRegistry: 'acr-sc'
    repository: '$(acrName)/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(System.DefaultWorkingDirectory)/react-and-spring-data-rest/Dockerfile.react'
    tags: '$(Build.BuildId)'
  displayName: 'Build and Push Docker Image'

- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'SrikanthNamoju'
    azureResourceGroup: 'CG-rg'
    kubernetesCluster: 'CG5677akscluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8s/frontend-react-deployment.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
