{
 "title": "Docker 101",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Docker App Instances",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"app\"}"
    }
   ]
  },
  {
   "title": "Prometheus Instances",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Docker App Request Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "dockerapp_numOfRequests{job=\"app\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Prometheus Scraped Targets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{config!=\"prometheus\"}",
     "legendFormat": "{{config}}"
    }
   ]
  }
 ]
}