apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grid-default
  namespace: apps
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/grid-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/grid-default: "true"
