{
 "title": "Kubernetes 101",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "App interaction ITEMS",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dockerapp_pathsTaken{instance=\"app.apps:8080\",job=\"k8sapp-default\",path=\"/items\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "dockerapp_pathsTaken", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "App Interaction TODO list",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerapp_numOfRequests{instance=\"app.apps:8080\",job=\"k8sapp-default\",method=\"GET\"}\t",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "dockerapp_numOfRequests{instance=\"app.apps:8080\",job=\"k8sapp-default\",method=\"POST\"}\t",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "dockerapp_numOfRequests{instance=\"app.apps:8080\",job=\"k8sapp-default\",method=\"DELETE\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Graph interaction app TODO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 11 },
   "targets": [
    { "expr": "dockerapp_numOfRequests", "legendFormat": "{{method}}" }
   ]
  }
 ]
}