---
apiVersion: v1
kind: Secret
metadata:
  name: webserver-decode-secret
type: Opaque
data:
  # Must be base64 encoded
  FERNET_KEY: cG9uOGpLMTdPVUZNRUpJaGFLX0RNekxRRHdDNmFMa2ZXQVN3ZkJwVWJwST0=
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
spec:
  containers:
  - name: mycontainer
    image: python:3-buster
    command: ["/bin/bash"]
    args: ["-c","pip install -r /webserver/requirements.txt; python /webserver/server.py"]
    # Missing: Volume mount for /webserver (mount or configmap file)
    # Missing: Environment variable for SECRET_KEY (to use webserver-decode-secret's FERNET_KEY)
    ports:
      - containerPort: 6677
