apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: apps
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  - port: 4000
    targetPort: 4000
    name: app
  selector:
    app: app
